//LOCALHOST
### Get all games
GET http://localhost:3000/games

### Get a game by ID
GET http://localhost:3000/games/682c18054e1814add9ad1875
### Get a game by ID
GET http://localhost:3000/games/682c18804e1814add9ad1876

### Create a new game
POST http://localhost:3000/games HTTP/1.1
Content-Type: application/json

{
    "title": "Dark Souls III",
    "studio": "FromSoftware",
    "releaseDate": "03/24/2016",
    "rating": "M",
    "genre": "Action RPG"
}

### Update a game by ID
PUT http://localhost:3000/games/682d3b2ec5a05573a9c4dcf4 HTTP/1.1
Content-Type: application/json

{
  "title": "Dark Souls: Remastered",
  "studio": "FromSoftware",
  "releaseDate": "2018/05/23",
  "rating": "M",
  "genre": "Action RPG"
}

### Delete a game by ID
DELETE http://localhost:3000/games/682d3b2ec5a05573a9c4dcf4 HTTP/1.1


//RENDER DEPLOYMENT
### Get all contacts
GET https://project2-8ncx.onrender.com/games

### Get a contact by ID
GET https://project2-8ncx.onrender.com/games/682c1a42bdbd49c869865bb2